# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170328_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='timezone',
            field=models.CharField(choices=[('America/Bogota', 'America/Bogota'), ('(UTC-0800) America/Los_Angeles', 'America/Los_Angeles')], default='America/Bogota', max_length=255),
        ),
    ]
