# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170503_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateTimeField(max_length=255),
        ),
    ]
