# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 04:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20170505_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 5, 5, 38, 9, 624026)),
        ),
    ]
