# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 23:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20170505_0438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date_start',)},
        ),
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 7, 0, 9, 10, 155440)),
        ),
    ]
