# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('personal_skills', models.CharField(max_length=500)),
                ('team_skills', models.CharField(max_length=500)),
                ('weakness', models.CharField(max_length=500)),
                ('illness', models.CharField(max_length=500)),
                ('under_presure', models.CharField(max_length=500)),
                ('photo', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
